# Generated by Django 4.1.5 on 2023-01-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_pacientes_id_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='id_persona',
        ),
    ]
