# Generated by Django 4.1.5 on 2023-01-26 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_personas_delete_persona'),
        ('pacientes', '0003_remove_pacientes_id_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='id_persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='personas.personas'),
            preserve_default=False,
        ),
    ]
