# Generated by Django 4.1.5 on 2023-01-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_pacientes_id_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='id',
        ),
        migrations.AddField(
            model_name='pacientes',
            name='id_paciente',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='sintomas',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
